version: 0.0
os: linux

files:
  - source: app.jar
    destination: /opt/schedemy

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: root

